### ISSUE TITLE
Le module ne semble plus compatible avec la version 10 de foundry

### ISSUE THREAD

**Issue by yann-berthaux** [Padhiver/Aventure-en-Terre-du-Milieu#1]
Le module ne semble plus compatible avec la version 10 de foundry

foundry.js:58305 L'installation a échoué : Could not fetch Package
fetch @ foundry.js:58305
notify @ foundry.js:58232
error @ foundry.js:58268
error @ setup.js:289
(anonymous) @ setup.js:343
setup.js:290 Error: Could not fetch Package
    at Module.installPackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1532)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SetupView.handlePost (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:1980)

**Comment by yann-berthaux** [comment]
PS (et merci pour le travail qui a déjà été effectué :-) )

**Comment by Padhiver** [comment]
Salut !
Je regarde ça dès que je peux, ça ne devrait pas prendre très longtemps.

**Comment by Padhiver** [comment]
Petite update, une release (0.2) est dispo' sur le git, mais j'attends que Foundry règle un soucis de compendium vide avant de release une version officielle au cas ou il faudrait changer certaines choses, mais en attendant, elle est dispo'.
